# CabsOnline Part 2

## Public URL
Public deployed application URL: https://web-dev-assignment-2-part-2.vercel.app/

Local development URL used for testing: `http://localhost:3001`

## Standalone Part 2 Scope
CabsOnline Part 2 is a standalone modern web application inspired by the Part 1 taxi booking workflow. It does not reconnect to the Part 1 PHP/MySQL backend, does not use localStorage, and stores booking data in Supabase.

## Technology Stack
- Framework: Next.js 16.2.6 with App Router
- UI library: React 19.2.4 and React DOM 19.2.4
- Language: TypeScript 5
- Database/client: Supabase with `@supabase/supabase-js` 2.106.2
- Map: Leaflet 1.9.4 using OpenStreetMap/CARTO raster tiles
- Address search: Nominatim/OpenStreetMap search API, restricted to New Zealand
- Icons: lucide-react 1.16.0
- Styling: global CSS in `app/globals.css`

## Local Setup
Create `.env.local` with Supabase browser-safe keys:

```bash
NEXT_PUBLIC_SUPABASE_URL=your_supabase_project_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
```

The app also supports `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY` as a fallback key name.

Install and run:

```bash
npm install
npm run dev
```

Build for production:

```bash
npm run build
```

## Database
Supabase table: `cabsonline_bookings`

Required columns:

```sql
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
booking_ref TEXT UNIQUE NOT NULL,
cname TEXT NOT NULL,
phone TEXT NOT NULL,
unumber TEXT,
snumber TEXT NOT NULL,
stname TEXT NOT NULL,
sbname TEXT,
dsbname TEXT,
pickup_address TEXT,
destination_address TEXT,
pickup_lat DOUBLE PRECISION,
pickup_lon DOUBLE PRECISION,
destination_lat DOUBLE PRECISION,
destination_lon DOUBLE PRECISION,
pickup_date DATE NOT NULL,
pickup_time TIME NOT NULL,
booking_datetime TIMESTAMP DEFAULT NOW(),
status TEXT DEFAULT 'unassigned',
payment_method TEXT DEFAULT 'Card',
payment_status TEXT DEFAULT 'pending',
driver_id TEXT,
driver_name TEXT,
driver_car TEXT,
driver_plate TEXT,
estimated_fare NUMERIC,
tracking_step INTEGER DEFAULT 1
```

## Microservice And API Endpoints
- Supabase database API: used through `lib/supabaseClient.ts` for booking persistence, payment status updates, driver assignment, tracking updates, and clearing demo data.
- Nominatim address API: `https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&limit=5&countrycodes=nz&q=...`
- OpenStreetMap/CARTO tile service: `https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png`
- Leaflet marker assets: `https://unpkg.com/leaflet@1.9.4/dist/images/...`

## Main Features
1. Real map-based interaction: booking and tracking views display pickup and destination markers plus a route line on an interactive Leaflet map.
2. NZ address autocomplete: pickup and destination fields call Nominatim, restrict results to New Zealand, fill address fields, and update map coordinates.
3. Driver/admin management: `/admin` is protected by demo login and supports active booking search, available-driver assignment, driver availability, and clearing demo data.
4. Customer tracking: customers can search by booking reference and see booking received, driver assigned, driver on the way, and trip completed states.
5. Customer-side payment processing: customers pay from the tracking panel; admin cannot process payment.
6. Driver login/workflow: `/driver` lets drivers log in with a demo driver ID, view their trips, and update tracking by confirming on the way, picked up, or finished.

## Routes
- `/`: customer dashboard with Booking, Customer Tracking, Drivers, and Map views.
- `/admin`: admin login and admin dashboard.
- `/driver`: driver login and driver dashboard.

## Demo Credentials
Admin:
- Username: `admin`
- Password: `cabsonline123`

Sample driver IDs:
- `DRV001` Aman Singh
- `DRV002` Sarah Lee
- `DRV003` Mo Ahmed
- `DRV004` James Wilson

## Example Booking References
Booking references are generated incrementally:
- `BRN00001`
- `BRN00002`
- `BRN00003`

Use the actual reference shown in the booking confirmation message when testing tracking.

## Testing Instructions
1. Run `npm run dev`.
2. Open the customer app at `http://localhost:3000` or the port shown by Next.js.
3. Create a booking using NZ address autocomplete for pickup and destination.
4. Confirm address suggestions appear quickly and close after selecting.
5. Confirm the map shows pickup/destination markers and a line.
6. Copy the booking reference from the confirmation message.
7. Open `/admin` and log in with `admin` / `cabsonline123`.
8. Confirm the active booking appears and completed/elapsed bookings are hidden.
9. Assign an available driver.
10. Return to Customer Tracking, search the booking reference, and pay.
11. Open `/driver` and log in with the assigned driver ID.
12. Confirm On The Way and check Customer Tracking shows the driver-on-the-way step.
13. Finish Drive and confirm the booking is completed.
14. Confirm the completed booking disappears from the active admin list.
15. Confirm the driver becomes available again when no assigned trip is within the next hour.
16. Run `npm run build` and confirm it completes successfully.

## Requirement Audit
- Supabase persistence: complete. Bookings are loaded, inserted, updated, and deleted through Supabase.
- Booking save: complete. New bookings insert into `cabsonline_bookings`.
- Driver assignment: complete. Admin assignment updates `status`, driver fields, and `tracking_step`.
- Customer tracking updates: complete. Customer and driver progress actions update Supabase.
- Active admin filtering: complete. Completed and elapsed bookings are excluded.
- Driver availability: complete. Availability is calculated from assigned bookings within the next hour.
- Customer-side payment: complete. Payment is only available in Customer Tracking.
- Admin separation: complete. Admin features are behind `/admin` login.
- Driver separation: complete. Driver features are behind `/driver` login.
- Responsive UI: complete. Layouts collapse to one column on smaller screens.

## Known Limitations
- Demo admin and driver login are hardcoded and are not secure production authentication.
- Payment is simulated by setting `payment_status = paid`; no external payment gateway is integrated.
- Booking reference generation is incremental from loaded Supabase bookings and is suitable for the assignment demo, but a production app should generate references transactionally on the server.
- Nominatim is a public geocoding service and may rate-limit heavy use.
- The map draws a straight line between pickup and destination rather than road-routing.

## AI-Supported Development Reflection
AI assistance was used during development to help debug errors, check the Part 2 requirements, and compare whether the existing AUT webdev/MySQL server or Supabase would be more suitable for a standalone deployed app. It was also used to help structure the README.DOC and review whether the project covered the required features. The final implementation, testing, and project decisions were manually reviewed.
